spring:
  application:
    name: bkk-backup-service
  main:
    banner-mode: "off"
  kafka:
    topics:
      refinedBkk: refinedBKK
    bootstrap-servers: localhost:9092
    consumer:
      group-id: bkk-backup
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  data:
    mongodb:
      database: routes-backup
      authentication-database: routes-backup
      username: routeManager
      password: route123
      port: 27017
      host: localhost

management:
  server:
    port: 9001
  endpoint:
    health:
      show-details: "ALWAYS"
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}

server:
  port: 8008
  servlet:
    application-display-name: "BKK"
    context-path: /bkk

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: FULL
  httpclient:
    follow-redirects: false

